# Generated by Django 2.2.19 on 2022-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('birth_place', models.CharField(max_length=200)),
                ('pass_serie', models.IntegerField(max_length=4)),
                ('pass_number', models.IntegerField(max_length=6)),
                ('division_code', models.CharField(max_length=15)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('whom_issued', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('bank_name', models.CharField(max_length=500)),
                ('bank_data', models.DateTimeField(auto_now_add=True)),
                ('contract_number', models.CharField(max_length=50)),
            ],
        ),
    ]
