# Generated by Django 2.2.19 on 2022-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='division_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='statement',
            name='pass_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statement',
            name='pass_serie',
            field=models.IntegerField(),
        ),
    ]
