# Generated by Django 2.2.19 on 2022-09-16 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_auto_20220913_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='contract_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='bank_data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='statement',
            name='birth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statement',
            name='issue_date',
            field=models.DateTimeField(),
        ),
    ]
