# Generated by Django 2.2.19 on 2022-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_auto_20220919_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='birth_date',
            field=models.DateField(default='01.01.1990'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='contract_date',
            field=models.DateField(default='01.01.2022'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='issue_date',
            field=models.DateField(default='01.01.2010'),
        ),
    ]
