# Generated by Django 2.2.19 on 2022-09-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_auto_20220919_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='pass_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='statement',
            name='pass_serie',
            field=models.CharField(max_length=4),
        ),
    ]
